image: docker:latest

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Xmx2g -Dmaven.repo.local=.m2"
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build

test:
  image: terrestris/gitlab-runner-image:jdk11-mvn-3.6-3
  stage: test
  script:
    - mvn -v
    - mvn clean test -B

build:
  image: terrestris/gitlab-runner-image:jdk11-mvn-3.6-3
  stage: build
  only:
    - master@terrestris/bkg-testsuite
    - tags
  script:
    - mkdir -p .m2
    - echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"><servers><server><id>nexus.terrestris.de-releases-hermosa</id><username>gs-deploy</username><password>$NEXUS_PASSWORD</password></server><server><id>nexus.terrestris.de-snapshots-hermosa</id><username>gs-deploy</username><password>$NEXUS_PASSWORD</password></server><server><id>nexus.terrestris.de</id><username>gs-deploy</username><password>$NEXUS_PASSWORD</password></server></servers></settings>" > .m2/settings.xml
    - mvn -v
    - mvn --settings .m2/settings.xml -B -P reporting surefire-report:report site site:jar deploy
    - mvn --settings .m2/settings.xml -B -Dsonar.password=$SONAR_PASSWORD sonar:sonar
